"""Initial schema: departments, monthly workforce rows, import provenance.

Revision ID: 0001
Revises:
Create Date: 2026-09-29

Written by hand rather than autogenerated so every constraint is deliberate.
Constraint names follow the naming convention in
``pbo_workforce.db.tables.Base`` so the models and this migration compare
equal (``tests/integration/test_migrations.py``). CHECK names are wrapped in
``op.f()`` because the convention would otherwise prefix them a second time.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Enum values are literals here, not imported from the application, so this
# migration keeps describing the schema as it was when it was written.
_TENURE = postgresql.ENUM(
    "indeterminate",
    "term",
    "casual",
    "student",
    "missing",
    "combined",
    name="tenure",
    create_type=False,
)
_SOURCE = postgresql.ENUM("fps", "rcmp", "caf", name="source", create_type=False)
_BATCH_STATUS = postgresql.ENUM(
    "succeeded", "failed", name="batch_status", create_type=False
)
_ENUMS = (_TENURE, _SOURCE, _BATCH_STATUS)


def upgrade() -> None:
    """Create enums, tables, constraints, and indexes."""
    bind = op.get_bind()
    for enum in _ENUMS:
        enum.create(bind)

    op.create_table(
        "department",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("long_name_en", sa.Text(), nullable=False),
        sa.Column("long_name_fr", sa.Text(), nullable=False),
        sa.Column("short_name_en", sa.Text(), nullable=True),
        sa.Column("short_name_fr", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_department"),
        sa.UniqueConstraint("long_name_en", name="uq_department_long_name_en"),
    )

    op.create_table(
        "department_alias",
        sa.Column("alias_normalized", sa.Text(), nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("alias_normalized", name="pk_department_alias"),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["department.id"],
            name="fk_department_alias_department_id_department",
        ),
    )

    op.create_table(
        "import_batch",
        sa.Column("id", sa.Integer(), sa.Identity(), nullable=False),
        sa.Column("file_sha256", sa.String(64), nullable=False),
        sa.Column("file_name", sa.Text(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column[str]("status", _BATCH_STATUS, nullable=False),
        sa.Column("counts", postgresql.JSONB(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_import_batch"),
    )
    op.create_index("ix_import_batch_file_sha256", "import_batch", ["file_sha256"])

    op.create_table(
        "workforce_monthly",
        sa.Column("id", sa.BigInteger(), sa.Identity(), nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=False),
        sa.Column("period", sa.Date(), nullable=False),
        sa.Column[str]("tenure", _TENURE, nullable=False),
        sa.Column[str]("source", _SOURCE, nullable=False),
        sa.Column("headcount", sa.Integer(), nullable=False),
        sa.Column("fte", sa.Double[float](), nullable=True),
        sa.Column("import_batch_id", sa.Integer(), nullable=False),
        sa.Column("source_sheet", sa.Text(), nullable=False),
        sa.Column("source_row", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_workforce_monthly"),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["department.id"],
            name="fk_workforce_monthly_department_id_department",
        ),
        sa.ForeignKeyConstraint(
            ["import_batch_id"],
            ["import_batch.id"],
            name="fk_workforce_monthly_import_batch_id_import_batch",
        ),
        sa.UniqueConstraint(
            "department_id",
            "period",
            "tenure",
            "source",
            name="uq_workforce_monthly_department_id_period_tenure_source",
        ),
        sa.CheckConstraint(
            "headcount >= 0", name=op.f("ck_workforce_monthly_headcount_non_negative")
        ),
        sa.CheckConstraint(
            "fte >= 0", name=op.f("ck_workforce_monthly_fte_non_negative")
        ),
        sa.CheckConstraint(
            "extract(day from period) = 1",
            name=op.f("ck_workforce_monthly_period_first_of_month"),
        ),
        sa.CheckConstraint(
            "(source = 'fps' AND fte IS NOT NULL AND tenure <> 'combined')"
            " OR (source <> 'fps' AND fte IS NULL AND tenure = 'combined')",
            name=op.f("ck_workforce_monthly_source_shape"),
        ),
    )
    # Serves the FTE query: one department and source, scanned by period.
    op.create_index(
        "ix_workforce_monthly_department_id_source_period",
        "workforce_monthly",
        ["department_id", "source", "period"],
    )

    for table in ("import_rejection", "import_warning"):
        op.create_table(
            table,
            sa.Column("id", sa.BigInteger(), sa.Identity(), nullable=False),
            sa.Column("batch_id", sa.Integer(), nullable=False),
            sa.Column("sheet", sa.Text(), nullable=False),
            sa.Column("source_row", sa.Integer(), nullable=False),
            sa.Column("reason_code", sa.Text(), nullable=False),
            sa.Column("detail", sa.Text(), nullable=False),
            sa.Column("raw", postgresql.JSONB(), nullable=False),
            sa.PrimaryKeyConstraint("id", name=f"pk_{table}"),
            sa.ForeignKeyConstraint(
                ["batch_id"],
                ["import_batch.id"],
                name=f"fk_{table}_batch_id_import_batch",
            ),
        )
        op.create_index(f"ix_{table}_batch_id", table, ["batch_id"])


def downgrade() -> None:
    """Drop everything ``upgrade`` created, in dependency order."""
    for table in (
        "import_warning",
        "import_rejection",
        "workforce_monthly",
        "import_batch",
        "department_alias",
        "department",
    ):
        op.drop_table(table)
    bind = op.get_bind()
    for enum in reversed(_ENUMS):
        enum.drop(bind)
